// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzTNg9gN7DyVjw_TL9r_Htce8zuhSLHq4',
    appId: '1:745674456530:web:c021bda0f8451f27c8dc0b',
    messagingSenderId: '745674456530',
    projectId: 'littlebank-156ec',
    authDomain: 'littlebank-156ec.firebaseapp.com',
    storageBucket: 'littlebank-156ec.firebasestorage.app',
    measurementId: 'G-EKQ2DHZ0FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzlnUUg6V2JrLQxtF5qM4UjRjsBLGbghA',
    appId: '1:745674456530:android:1dad68e008f22d72c8dc0b',
    messagingSenderId: '745674456530',
    projectId: 'littlebank-156ec',
    storageBucket: 'littlebank-156ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGsUMHVvXjKDnhNmpJV0FcX0fnEyQ8ai8',
    appId: '1:745674456530:ios:30e505035686c540c8dc0b',
    messagingSenderId: '745674456530',
    projectId: 'littlebank-156ec',
    storageBucket: 'littlebank-156ec.firebasestorage.app',
    iosBundleId: 'com.example.androidDesignPreview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGsUMHVvXjKDnhNmpJV0FcX0fnEyQ8ai8',
    appId: '1:745674456530:ios:30e505035686c540c8dc0b',
    messagingSenderId: '745674456530',
    projectId: 'littlebank-156ec',
    storageBucket: 'littlebank-156ec.firebasestorage.app',
    iosBundleId: 'com.example.androidDesignPreview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzTNg9gN7DyVjw_TL9r_Htce8zuhSLHq4',
    appId: '1:745674456530:web:94f8238621cf300bc8dc0b',
    messagingSenderId: '745674456530',
    projectId: 'littlebank-156ec',
    authDomain: 'littlebank-156ec.firebaseapp.com',
    storageBucket: 'littlebank-156ec.firebasestorage.app',
    measurementId: 'G-MZ3G8JL9ZP',
  );
}
